name: Build Srun Login Tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Srun Tool
        run: |
          # 1. 设置编译目标为 K2P 的架构
          export GOOS=linux
          export GOARCH=mipsle
          export GOMIPS=softfloat
          
          # 2. 编译当前目录下的 main.go
          go build -ldflags "-s -w" -o srun_login main.go
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: srun_login_k2p
          path: srun_login
